# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-07 03:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam5', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('trip_start', models.DateField()),
                ('trip_end', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='users',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='users',
            name='email',
        ),
        migrations.AddField(
            model_name='trips',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_organizer', to='exam5.Users'),
        ),
        migrations.AddField(
            model_name='trips',
            name='trip_joiner',
            field=models.ManyToManyField(related_name='joining_trip', to='exam5.Users'),
        ),
    ]
