# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-07 05:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam5', '0002_auto_20180106_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trips',
            name='trip_joiner',
        ),
        migrations.AddField(
            model_name='trips',
            name='trip_joiner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='joining_trip', to='exam5.Users'),
        ),
    ]
