# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-07 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam5', '0003_auto_20180106_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trips',
            name='trip_joiner',
        ),
        migrations.AddField(
            model_name='trips',
            name='trip_joiner',
            field=models.ManyToManyField(related_name='joining_trip', to='exam5.Users'),
        ),
    ]
